### ISSUE TITLE
Create a branch for SVG Assets

### ISSUE THREAD

**Issue by BrianSipple** [emberjs/design#1]
It would be really useful to have one central place for Ember's SVG assets -- at least those that we're intending to allow usage of. 

Right now, this would consist of logos -- but it could even consist of specialized icons, or any SVG artwork at some point. I have a [branch in my fork](https://github.com/BrianSipple/design/tree/svg-assets) where I converted the [PNG logos provided on the website](http://emberjs.com/logos/) into SVGs and named them appropriately. 

Having that space here could just serve as a quick way to grab the assets, but it could also lead to creating something like the aforementioned page on our website that showcases _and_ offers a download link for everything.

**Comment by wifelette** [comment]
https://github.com/emberjs/whiteboard/tree/design-svg-assets

With all new branches, I can add people to permissions teams as needed. The intent is NOT for the core/learning folk to be the only ones who can merge things, that would slow everything down. So we'll create new teams and add people to them as needed :) Probably the first time someone needs to submit a PR they should ask for the permissions there too and someone who already has them can add.
