### ISSUE TITLE
Create a branch for ember video projects

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/design#6]
TODO @gavinjoyce:

 * [x] create a branch which includes [this content](https://usecanvas.com/gavinjoyce/impactful-emberjs-videos/4D4pYK9DIbBr456t0r6y7l) and other related content.
 * [x] include video resources such as [transitions, logos and sounds](https://drive.google.com/open?id=0B9okRbkfiBURVkFyQmx1RHBFdVk) used in previous videos

**Comment by wifelette** [comment]
To be sure, you don't need anything from me to get this done, right? Let me know if I made any mistakes with the permissions but you should have access to doing it all :)

**Comment by GavinJoyce** [comment]
@wifelette I don't need anything, thanks. This is a todo list for me, my output increases every time I have one

**Comment by GavinJoyce** [comment]
https://github.com/emberjs/whiteboard/pull/7
